### ISSUE TITLE
Could not find .osu file

### ISSUE THREAD

**Issue by aka91x** [thebetioplane/OsuReplayEditorV2#3]
![editor_2018-12-27_13-28-20](https://user-images.githubusercontent.com/30756754/50480311-719b4600-09db-11e9-8679-21e71b17623b.png)
No matter what replay I choose, this error pops up.
The songs folder location is specified correctly in the config.
Thanks in advance

**Comment by thebetioplane** [comment]
I have created a version 3 to address many problems : https://github.com/thebetioplane/osuReplayEditorV3
