### ISSUE TITLE
plz add key presses into it

### ISSUE THREAD

**Issue by Sun5hine1** [thebetioplane/OsuReplayEditorV2#4]

**Comment by thebetioplane** [comment]
The chances of me updating anything in this code base are very slim, I haven't even had a C# + XNA environment set up for quite some time now. My motivation for making the editor more robust is low as well... I don't even cheat osu myself, I made the replay editor originally out of curiosity, to closely analyze replays and compare them, and of course to send people fake replays of something you never accomplished.

However, if someone did a pull request I may reconsider.

**Comment by Sun5hine1** [comment]
Do it please! :)

**Comment by thebetioplane** [comment]
I have created a version 3 to address many problems : https://github.com/thebetioplane/osuReplayEditorV3
